package Net::SSH::Server;

use strict;
use warnings;
our $VERSION = '0.021';

use FindBin qw($Script);
use Fcntl qw(O_CREAT O_EXCL O_RDONLY O_RDWR O_WRONLY);

# Method: new
# Purpose: Initializer
sub new {
    my $class = shift;
    my $self = shift || {};
    bless $self, $class;
    $self->{run} = [ $0, @ARGV ];
    $self->init;
    return bless $self, $class;
}

# Method: init
# Purpose: Run when a new instance is created
# Default is to do nothing
sub init {}

sub run {
    my $self = shift || __PACKAGE__;
    # Make sure $self is a real object instead of just a class
    ref $self or $self = $self->new;
    # Detect pam_exec case
    if (1 < @{ $self->{run} } and $self->{run}->[1] =~ /^pam_exec_step=(.+)/) {
        eval { $self->generate_pam_config } if !-f $self->pam_file;
        $self->{pam_id} = getppid();
        exit $self->run_pam_exec;
    }
    # Detect missing "-D" case, then Detach and launch WITH "-D":
    if (!grep { $_ eq "-D" } @{ $self->{run} }) {
        splice @{ $self->{run} }, 1, 0, "-D";
        exit if fork;
    }
    # Now we know it's the perfect non-detach mode to allow easy monitoring
    $ENV{NET_SSH_EXEC_PID} = $$;
    $self->{pam_id} = $ENV{NET_SSH_SERVICE} ? $$ : "master-".($ENV{NET_SSH_SERVICE}=$self->pam_service);
    exit $self->run_sshd;
}

sub pam_args {
    my $self = shift;
    return $self->{pam_args} ||= do {
        my $args = {};
        for (my $i = 1; $i < @{ $self->{run} }; $i++) {
            if ($self->{run}->[$i] =~ /^(\w+)=(.*)/) {
                $args->{$1} = $2;
            }
        }
        $args;
    };
}

sub session_file {
    my $self = shift;
    return $self->{session_file} ||= "/var/run/sshd/session-$self->{pam_id}.env";
}

sub pam_getenv {
    my $self = shift;
    my $name = shift // "";
    if (sysopen my $fh, $self->session_file, O_RDONLY, 0600) {
        my $contents = join "", <$fh>;
        close $fh;
        while ($contents =~ s/^(\w+)=(.*)\n//) {
            my $n = $1;
            my $v = $2;
            $v =~ s/\\n/\n/g;
            $ENV{$n} = $v;
        }
    }
    return $ENV{$name};
}

sub pam_putenv {
    my $self = shift;
    my $name = shift;
    my $value = shift // "";
    my $old_value = $self->pam_getenv($name) // "";
    return $self if $old_value eq $value;
    $ENV{$name} = $value;
    my $file = $self->session_file;
    my $prev = {};
    sysopen my $fh, $file, O_CREAT | O_RDWR, 0600 or die "$file: open failure! $!\n";
    my $contents = join "", <$fh>;
    $value =~ s/\n/\\n/g;
    $contents .= "$name=$value\n";
    while ($contents =~ s/^(\w+)=(.*)\n//) {
        $prev->{$1} = $2;
    }
    $contents = "";
    foreach my $n (sort keys %$prev) {
        $contents .= "$n=$prev->{$n}\n";
    }
    seek $fh, 0, 0; # SEEK_SET
    print $fh $contents;
    truncate($fh, tell $fh);
    close $fh;
    return $self;
}

sub run_pam_exec {
    my $self = shift;
    my $type = $ENV{PAM_TYPE} or die "pam_exec: type failure\n";
    my $step = $self->pam_args->{pam_exec_step} or die "pam_exec: step failure\n";
    $step =~ s/-/_/g;
    my $method = "$type\_$step";
    my $code = $self->can($method) || "";
    $self->trace("run_pam_exec:[method=$method][code=$code]");
    $code ||= sub {0}; # PAM_SUCCESS
    $self->loadstash;
    $self->trace("run_pam_exec:[loadstash=".($self->session_file)."]");
    return [$code->($self), $self->trace("run_pam_exec:savestash"), $self->savestash]->[0];
}

sub run_sshd {
    my $self = shift;
    $self->trace("run_sshd:TopOverRide=[".($ENV{NET_SSH_OVERRIDE} // "(undef)")."]");
    if ($ENV{NET_SSH_OVERRIDE}) {
        # Already munged
    }
    else {
        my $dir = $self->stash->{override_config_directory};
        $dir = undef if $dir and !-d $dir;
        my $file = $self->stash->{override_config_file};
        $file = undef if $file and !-e $file;
        if ($dir) {
            $file ||= "/etc/ssh/sshd_config";
            $ENV{NET_SSH_OVERRIDE} = "/var/run/sshd/".$self->pam_service().".conf";
            open my $cnf, ">", $ENV{NET_SSH_OVERRIDE};
            print $cnf "# DO NOT EDIT MANUALLY!\n";
            print $cnf "# Auto-generated by $0\n";
            print $cnf "# Override settings using any *.conf file under $dir/\n";
            print $cnf "Include $dir/*.conf\n";
            print $cnf "Include $file\n" if $file;
            close $cnf;
        }
        elsif ($file) {
            $ENV{NET_SSH_OVERRIDE} = $file;
        }
        else {
            $ENV{NET_SSH_OVERRIDE} = "/dev/null";
        }
        push @{ $self->{run} }, (-f => $ENV{NET_SSH_OVERRIDE}) if $dir || $file;
    }
    my $target = $self->target;
    die "$target: Not executable\n" if !-x $target;
    die "$0: Invalid invocation\n" if $target eq $self->{run}->[0];
    $self->trace("run_sshd:EndOverRide=[".($ENV{NET_SSH_OVERRIDE} // "(undef)")."]");
    exec { $target } @{ $self->{run} } or die "$0: spawn failure: $!\n";
}

sub target {
    return shift()->stash->{target} ||= eval { require File::Which; File::Which::which("sshd") } || "/usr/sbin/sshd";
}

sub stash {
    my $self = shift;
    return $self->{stash} ||= {};
}

sub pam_service {
    return $ENV{PAM_SERVICE} ||= $Script;
}

sub pam_file {
    "/etc/pam.d/".pam_service();
}

sub auth_sniff {
    my $self = shift;
    $self->trace("auth_sniff");
    return 0; # PAM_SUCCESS
}

sub auth_check {
    my $self = shift;
    $self->trace("auth_check:top");
    my $pw = <STDIN> // "";
    $self->pam_putenv( PAM_PW => $pw );
    push @{ $self->stash->{auth_pw} ||= [] }, $pw;
    $self->trace("auth_check:end");
    return $self->validate_pw;
}

sub validate_nonempty {
    my $self = shift;
    my $pw = $ENV{PAM_PW} // "";
    # Return SUCCESS if any random non-empty password is provided
    return length $pw ?
        0 : # PAM_SUCCESS   /* Successful function return */
        7 ; # PAM_AUTH_ERR  /* Authentication failure */
}

# When "PasswordAuthentication yes" is enabled, then check passwd provided.
# Return PAM_* error code or 0 [PAM_SUCCESS] if no problem:
sub validate_pw {
    my $self = shift;
    my $user = $ENV{PAM_USER}  or return 7; # PAM_AUTH_ERR  /* Authentication failure */
    my $pass = $ENV{PAM_PW};
    length ($pass // "")       or return 7; # PAM_AUTH_ERR  /* Authentication failure */
    my @pwent = getpwnam $user or return 7; # PAM_AUTH_ERR  /* Authentication failure */
    $pwent[1] && $pwent[1] =~ /^\$/;
    # Compare UNIX password to ensure it matches
    if (crypt($pass, $pwent[1]) eq $pwent[1]) {
        return 0;  # PAM_SUCCESS   /* Successful function return */
    }
    else {
        return 6;  # PAM_PERM_DENIED  /* Permission denied */
    }
}

sub account_sniff {
    my $self = shift;
    $self->trace("account_sniff");
    return 0; # PAM_SUCCESS
}

sub account_acquire_session_lock {
    my $self = shift;
    $self->trace("auth_acquire_session_lock");
    my $lock_file = $self->pam_args->{lockfile} or !warn "auth_acquire_session_lock lockfile missing\n" or return 14; # PAM_SESSION_ERR
    my $env_file  = $self->pam_args->{envfile}  or !warn "auth_acquire_session_lock envfile missing\n"  or return 14; # PAM_SESSION_ERR
    my $expire = 10 + time;
    my $save_env = "";
    if (open my $fh, "<", $self->session_file) {
        $save_env = join "", <$fh>;
        close $fh;
    }
    my $lock_goal = "$self->{pam_id}\n";
    if (open my $fh, "<", $lock_file) {
        if ((<$fh> || "") eq $lock_goal) {
            $lock_goal = "";
        }
        close $fh;
        if ($lock_goal and time() - [stat $lock_file]->[9] > 11) {
            # Get rid of crusty stale mismatched lock file
            unlink $lock_file;
        }
    }
    while ($lock_goal) {
        if (sysopen my $fh, $lock_file, O_WRONLY | O_CREAT | O_EXCL, 0600) {
            print $fh $lock_goal;
            close $fh;
            last;
        }
        select undef,undef,undef, 0.1;
        time > $expire and warn "$lock_file: FAILURE!\n" and return 22; # PAM_AUTHTOK_LOCK_BUSY
    }
    if (open my $fh, ">", $env_file) {
        print $fh $save_env;
        close $fh;
    }
    $self->savestash;
    return 0; # PAM_SUCCESS
}

# account pam_env burner runs after "account" phase and before "session" phase.

sub session_release_session_lock {
    my $self = shift;
    $self->trace("session_release_session_lock");
    my $lock_file = $self->pam_args->{lockfile} or !warn "account_release_session_lock lockfile missing\n" or return 14; # PAM_SESSION_ERR
    my $env_file  = $self->pam_args->{envfile}  or !warn "account_release_session_lock envfile missing\n"  or return 14; # PAM_SESSION_ERR
    unlink $env_file;
    unlink $lock_file;
    return 0; # PAM_SUCCESS
}

sub session_sniff {
    my $self = shift;
    $self->trace("session_sniff");
    return 0; # PAM_SUCCESS
}

sub json {
    my $self = shift;
    return $self->{json} ||= eval { require JSON; JSON->new->utf8->allow_unknown->allow_nonref->convert_blessed->canonical } || die "Could not load JSON: $@";
}

sub savestash {
    my $self = shift;
    $self->trace("savestash:top");
    $self->pam_putenv( STASH_JSON => $self->json->encode($self->stash) );
    $self->pam_putenv( SESSION_FILE => $self->session_file );
    $self->trace("savestash:end");
    return $self->stash;
}

sub loadstash {
    my $self = shift;
    my $json = $self->pam_getenv( "STASH_JSON" ) or return;
    $json = $self->json->decode($json);
    my $monkey_stash = 0;
    foreach my $k (keys %$json) {
        my $v = $self->stash->{$k};
        if ($v and "ARRAY" eq ref $v) {
            push @$v, $json->{$k};
            $monkey_stash++;
        }
        else {
            $self->stash->{$k} = $json->{$k};
        }
    }
    $self->savestash if $monkey_stash;
    return $self->stash;
}

sub trace {
    my $self = shift;
    my $tag = shift || "unknown_trace";
    # Nothing to do
}

1;
__END__
# Below is stub documentation for your module. You'd better edit it!

=head1 NAME

Net::SSH::Server - Perl extension for blah blah blah

=head1 SYNOPSIS

  use Net::SSH::Server;
  blah blah blah

=head1 DESCRIPTION

Stub documentation for Net::SSH::Server, created by h2xs. It looks like the
author of the extension was negligent enough to leave the stub
unedited.

Blah blah blah.

=head2 EXPORT

None by default.



=head1 SEE ALSO

Mention other useful documentation such as the documentation of
related modules or operating system documentation (such as man pages
in UNIX), or any relevant external documentation such as RFCs or
standards.

If you have a mailing list set up for your module, mention it here.

If you have a web site set up for your module, mention it here.

=head1 AUTHOR

Rob Brown, E<lt>bbb@cpan.orgE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2025 by Rob Brown

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.34.1 or,
at your option, any later version of Perl 5 you may have available.


=cut
