package Net::SSH::Server;

use strict;
use warnings;
our $VERSION = '0.021';

use FindBin qw($Script);
use Fcntl qw(O_CREAT O_EXCL O_RDWR O_WRONLY);
use IO::Handle;

sub new {
    my $class = shift;
    my $self = shift || {};
    bless $self, $class;
    $self->{run} = [ $0, @ARGV ];
    $self->init;
    return bless $self, $class;
}

# Method: init
# Purpose: Run when a new instance is created
# Default is to do nothing
sub init {}

sub run {
    my $self = shift || __PACKAGE__;
    ref $self or $self = $self->new;
    if (1 < @{ $self->{run} } and $self->{run}->[1] =~ /^pam_exec_step=(.+)/) {
        eval { $self->generate_pam_config } if !-f $self->pam_file;
        exit $self->run_pam_exec;
    }
    else {
        exit $self->run_sshd;
    }
}

sub pam_args {
    my $self = shift;
    return $self->{pam_args} ||= do {
        my $args = {};
        for (my $i = 1; $i < @{ $self->{run} }; $i++) {
            if ($self->{run}->[$i] =~ /^(\w+)=(.*)/) {
                $args->{$1} = $2;
            }
        }
        $args;
    };
}

sub session_file {
    my $self = shift;
    return $self->{session_file} if $self->{session_file};
    my $ppid_file = "/var/run/sshd/".getppid().".id";
    if ($self->{session_file} = $ENV{SESSION_FILE}) {
        $self->trace("session_file:[wiped_parent=$ppid_file]");
        unlink $ppid_file;
        return $self->{session_file};
    }
    return $self->{session_file} = $ENV{SESSION_FILE} = do {
        my $id;
        sysopen my $fh, $ppid_file, O_CREAT | O_RDWR, 0600 or die "$ppid_file: open failure! $!\n";
        if ($id = <$fh>) {
            chomp $id;
        }
        else {
            my $r = ['A'..'Z','a'..'z',0..9];
            $id = join "", map { $r->[rand @$r] } 1..20;
            seek $fh, 0, 0;
            print $fh "$id\n";
            $self->trace("session_file:[create_parent=$ppid_file]");
        }
        close $fh;
        "/var/run/sshd/$id.session";
    };
}

sub run_pam_exec {
    my $self = shift;
    my $type = $ENV{PAM_TYPE} or die "pam_exec: type failure\n";
    my $step = $self->pam_args->{pam_exec_step} or die "pam_exec: step failure\n";
    $step =~ s/-/_/g;
    my $method = "$type\_$step";
    -f $self->session_file;
    my $code = $self->can($method);
    $self->trace("run_pam_exec:[method=$method][".($code ? "Exists" : "NoMethod")."]");
    $code or return 0; # PAM_SUCCESS
    if (-f $self->session_file) {
        $self->loadstash;
    }
    $self->trace("run_pam_exec:[loadstash=".($self->session_file)."]");
    return [$code->($self), $self->trace("run_pam_exec:savestash"), $self->savestash]->[0];
}

sub run_sshd {
    my $self = shift;
    if ($ENV{NET_SSH_OVERRIDE}) {
        # Already munged
    }
    else {
        my $dir = $self->stash->{override_config_directory};
        $dir = undef if $dir and !-d $dir;
        my $file = $self->stash->{override_config_file};
        $file = undef if $file and !-e $file;
        if ($dir) {
            $file ||= "/etc/ssh/sshd_config";
            $ENV{NET_SSH_OVERRIDE} = "/var/run/sshd/".$self->pam_service().".conf";
            open my $cnf, ">", $ENV{NET_SSH_OVERRIDE};
            print $cnf "# DO NOT EDIT MANUALLY!\n";
            print $cnf "# Auto-generated by $0\n";
            print $cnf "# Override settings using any *.conf file under $dir/\n";
            print $cnf "Include $dir/*.conf\n";
            print $cnf "Include $file\n" if $file;
            close $cnf;
        }
        elsif ($file) {
            $ENV{NET_SSH_OVERRIDE} = $file;
        }
        else {
            $ENV{NET_SSH_OVERRIDE} = "/dev/null";
        }
        push @{ $self->{run} }, (-f => $ENV{NET_SSH_OVERRIDE}) if $dir || $file;
    }
    my $target = $self->target;
    die "$target: Not executable\n" if !-x $target;
    die "$0: Invalid invocation\n" if $target eq $self->{run}->[0];
    exec { $target } @{ $self->{run} } or die "$0: spawn failure: $!\n";
}

sub target {
    return shift()->stash->{target} ||= eval { require File::Which; File::Which::which("sshd") } || "/usr/sbin/sshd";
}

sub stash {
    my $self = shift;
    return $self->{stash} ||= {};
}

sub pam_service {
    return $ENV{PAM_SERVICE} ||= $Script;
}

sub pam_file {
    "/etc/pam.d/".pam_service();
}

sub auth_acquire_session_lock {
    my $self = shift;
    $self->trace("auth_acquire_session_lock");
    my $auths = $self->stash->{pam_auth} ||= [];
    my $pw = <STDIN>;
    defined $pw and chomp $pw;
    my $jam3 = IO::Handle->new_from_fd(3, ">");
    print $jam3 "\x00HACKJAM=$$\x00";
    close $jam3;
#$self->json->encode(

    push @{ $self->stash->{pam_auth} }, {
        auth_info => $ENV{SSH_AUTH_INFO_0},
        service   => $ENV{PAM_SERVICE},
        user      => $ENV{PAM_USER},
        pw        => $pw,
    };
    my $lock_file = $self->pam_args->{lockfile} or !warn "auth_acquire_session_lock lockfile missing\n" or return 14; # PAM_SESSION_ERR
    my $env_file  = $self->pam_args->{envfile}  or !warn "auth_acquire_session_lock envfile missing\n"  or return 14; # PAM_SESSION_ERR
    my $expire = 10 + time;
    while (1) {
        if (sysopen my $fh, $lock_file, O_WRONLY | O_CREAT | O_EXCL, 0600) {
            print $fh "$$\n";
            close $fh;
            if (open $fh, ">", $env_file) {
                print $fh "SESSION_FILE=$ENV{SESSION_FILE}\n" if !-f $ENV{SESSION_FILE};
                close $fh;
            }
            $self->savestash;
            last; # return 0; # PAM_SUCCESS
        }
        select undef,undef,undef, 0.1;
        time > $expire and warn "$lock_file: FAILURE!\n" and return 22; # PAM_AUTHTOK_LOCK_BUSY
    }
    return 0; # PAM_SUCCESS
}

sub auth_release_session_lock {
    my $self = shift;
    $self->trace("auth_release_session_lock");
    my $lock_file = $self->pam_args->{lockfile} or !warn "auth_acquire_session_lock lockfile missing\n" or return 14; # PAM_SESSION_ERR
    my $env_file  = $self->pam_args->{envfile}  or !warn "auth_acquire_session_lock envfile missing\n"  or return 14; # PAM_SESSION_ERR
    unlink $env_file;
    unlink $lock_file;
    return 0; # PAM_SUCCESS
}

sub auth_check {
    my $self = shift;
    $self->trace("auth_check");
    return 7; # PAM_AUTH_ERR /* Authentication failure */
}

sub json {
    my $self = shift;
    return $self->{json} ||= eval { require JSON; JSON->new->utf8->allow_unknown->allow_nonref->convert_blessed->canonical } || die "Could not load JSON: $@";
}

sub savestash {
    $ENV{SESSION_FILE} or return;
    my $self = shift;
    open my $fh, ">", $ENV{SESSION_FILE} or return;
    print $fh $self->json->encode($self->stash)."\n";
    close $fh;
    return $self->stash;
}

sub loadstash {
    my $self = shift;
    open my $fh, "<", $self->session_file or return;
    my $json = join "", <$fh>;
    close $fh;
    $json = $self->json->decode($json);
    foreach my $k (keys %$json) {
        my $v = $self->stash->{$k};
        if ($v and "ARRAY" eq ref $v) {
            push @$v, $json->{$k};
        }
        else {
            $self->stash->{$k} = $json->{$k};
        }
    }
    return $self->stash;
}

sub trace {
    my $self = shift;
    my $tag = shift || "unknown_trace";
    # Nothing to do
}

1;
__END__
# Below is stub documentation for your module. You'd better edit it!

=head1 NAME

Net::SSH::Server - Perl extension for blah blah blah

=head1 SYNOPSIS

  use Net::SSH::Server;
  blah blah blah

=head1 DESCRIPTION

Stub documentation for Net::SSH::Server, created by h2xs. It looks like the
author of the extension was negligent enough to leave the stub
unedited.

Blah blah blah.

=head2 EXPORT

None by default.



=head1 SEE ALSO

Mention other useful documentation such as the documentation of
related modules or operating system documentation (such as man pages
in UNIX), or any relevant external documentation such as RFCs or
standards.

If you have a mailing list set up for your module, mention it here.

If you have a web site set up for your module, mention it here.

=head1 AUTHOR

Rob Brown, E<lt>bbb@cpan.orgE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2025 by Rob Brown

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.34.1 or,
at your option, any later version of Perl 5 you may have available.


=cut
